actor_lr: 3e-4
actor_dropout: 0.1
batch_size: 256
beta: 3.0
buffer_size: 10000000
device: cuda
discount: 0.99
env: relocate-human-v1
eval_freq: 5000
group: iql-adroit-relocate-human-v1-multiseed-v0
iql_deterministic: false
iql_tau: 0.8
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: IQL
normalize: true
normalize_reward: false
qf_lr: 3e-4
project: CORL
seed: 0
tau: 0.005
vf_lr: 3e-4
