actor_init_w: 0.001
actor_lr: 0.0001
batch_size: 256
beta: 0.5
buffer_size: 2000000
checkpoints_path: ./models/spot
critic_init_w: 0.003
critic_lr: 0.0003
device: cuda
discount: 0.99
env: antmaze-large-play-v2
eval_freq: 50000
eval_seed: 0
expl_noise: 0.1
group: SPOT-D4RL
iwae: false
lambd: 0.025
lambd_cool: true
lambd_end: 0.2
load_model: ''
n_episodes: 100
name: SPOT
noise_clip: 0.5
normalize: false
normalize_reward: true
num_samples: 1
offline_iterations: 1000000
online_discount: 0.995
online_iterations: 1000000
policy_freq: 2
policy_noise: 0.2
project: CORL
seed: 0
tau: 0.005
vae_hidden_dim: 750
vae_iterations: 100000
vae_latent_dim: null
vae_lr: 0.001
