awac_lambda: 0.3333
batch_size: 256
buffer_size: 10000000
checkpoints_path: ./models/awac
deterministic_torch: true
device: cuda
env_name: hopper-full-replay-v2
eval_frequency: 1000
gamma: 0.99
group: AWAC-D4RL
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 10
num_train_ops: 1000000
project: CORL
seed: 42
tau: 0.005
test_seed: 69
use_wandb: true
